# Assignment : Numpy Assignemnt 

## 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [3]:
import numpy as np
arr=np.arange(6)
print(f"Array : {arr}\nArray data type : {arr.dtype}")

Array : [0 1 2 3 4 5]
Array data type : int32


## 2. Given a NumPy array 'arr', check if its data type is float64. 
##            arr = np.array([1.5, 2.6, 3.7])

In [6]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
print("Given a NumPy array 'arr' is float64") if (arr.dtype==np.float64) else print("Given a NumPy array 'arr' is not float64")    

Given a NumPy array 'arr' is float64


## 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
import numpy as np
arr=np.array([])
for i in range(3):
    a=complex(input(f"Enter C{i+1} : "))
    arr=np.append(arr,a)
arr=arr.astype("complex128")
arr.dtype

Enter C1 :  2+5j
Enter C2 :  -5
Enter C3 :  -2j


dtype('complex128')

##  4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [18]:
import numpy as np
arr=np.array([])
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    arr=np.append(arr,a)
arr=np.float32(arr)
arr.dtype

Enter the number of elements in array :  4
Enter integer number :  8
Enter integer number :  2
Enter integer number :  5
Enter integer number :  1


dtype('float32')

##  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [4]:
import numpy as np
arr=np.array([])
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=np.float64(input("Enter float number : "))
    arr=np.append(arr,a)
arr
float_arr=arr.astype(np.float32)
print(f"Array : {float_arr}\nArray data type : {float_arr.dtype}")

Enter the number of elements in array :  4
Enter float number :  8
Enter float number :  2
Enter float number :  5
Enter float number :  1


Array : [8. 2. 5. 1.]
Array data type : float32


## 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [32]:
import numpy as np
arr=np.array([])
n=int(input("Enter the number of elements in array : "))
row=int(input("Enter the number of rows in array : "))
col=int(input("Enter the number of columns in array : "))
for i in range(n):
    a=np.float64(input("Enter float number : "))
    arr=np.append(arr,a)
arr=arr.reshape(row,col)
def array_attributes(arr):
    return(f"Array : {arr}    Array shape : {arr.shape}    Array size : {arr.size}    Array data type :{arr.dtype}")
array_attributes(arr)

Enter the number of elements in array :  6
Enter the number of rows in array :  2
Enter the number of columns in array :  3
Enter float number :  1.2
Enter float number :  -1.2
Enter float number :  2.3
Enter float number :  -2.3
Enter float number :  3.4
Enter float number :  -3.4


'Array : [[ 1.2 -1.2  2.3]\n [-2.3  3.4 -3.4]]    Array shape : (2, 3)    Array size : 6    Array data type :float64'

## 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [33]:
import numpy as np
arr=np.array([[10,3],[3,7],[9,7.9]])
def array_dimension(arr):
    return(f"Array dimension : {arr.ndim}")
array_dimension(arr)

'Array dimension : 2'

## 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [4]:
import numpy as np
arr=np.array([[10,3],[3,7],[9,7.9]])
def item_size_info(arr):
    return(f"item size : {arr.itemsize}    total size : {arr.nbytes}")
item_size_info(arr)

'item size : 8    total size : 48'

## 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [6]:
import numpy as np
arr=np.array([[10,3],[3,7],[9,7.9]])
def array_strides(arr):
    return arr.strides
array_strides(arr)

(16, 8)

## 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [8]:
import numpy as np
arr=np.array([[10,3],[3,7],[9,7.9]])
def shape_stride_relationship(arr):
    return(f"Array shape : {arr.shape}    Array strides : {arr.strides}")
shape_stride_relationship(arr)

'Array shape : (3, 2)    Array strides : (16, 8)'

## 11. Create a function create_zeros_array that takes an integer 'n` as input and returns a NumPy array of zeros with 'n'elements.

In [7]:
import numpy as np
n=int(input("Enter the number of zerose in an array :"))
def create_zeros_array(n):
    return np.zeros((1,n))
create_zeros_array(n)

Enter the number of zerose in an array : 11


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 12. Write a function 'create_ones_matrix that takes integers 'rows' and cols' as inputs and generates a 2D NumPy array filled with ones of size 'rows x cols.

In [20]:
import numpy as np
rows=int(input("Enter the number of rows : "))
cols=int(input("Enter the number of cols : "))
def create_ones_matrix(rows,cols):
    return(np.ones((rows,cols)))
create_ones_matrix(rows,cols)

Enter the number of rows :  4
Enter the number of cols :  3


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from 'start', ending at stop (exclusive), and with the specified step.

In [21]:
import numpy as np
start=int(input("Enter the number of start : "))
stop=int(input("Enter the number of stop : "))
step=int(input("Enter the number of step : "))
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
generate_range_array(start,stop,step)

Enter the number of start :  1
Enter the number of stop :  11
Enter the number of step :  2


array([1, 3, 5, 7, 9])

## 14. Design a function generate_linear_space` that takes two floats 'start', stop', and an integer num as arguments and generates a NumPy array with num equally spaced values between 'start and 'stop' (inclusive).

In [8]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

start = float(input("Enter the starting value: "))
stop = float(input("Enter the stopping value: "))
num = int(input("Enter the number of values: "))

result = generate_linear_space(start, stop, num)
print(result)


Enter the starting value:  1
Enter the stopping value:  100
Enter the number of values:  10


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## 15. Create a function 'create_identity_matrix that takes an integer n` as input and generates a square identity matrix of size 'n x n`using numpy.eye.

In [9]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

n = int(input("Enter the value of n: "))
result = create_identity_matrix(n)
print(result)

Enter the value of n:  3


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 16. Write a function that takes a python list and converts it into Numpy array.

In [11]:
import numpy as np

def list_to_arr(list1):
    return np.array(list1)

list1 = []
n = int(input("Enter the number of elements: "))
for i in range(n):
    a = input(f"Enter element {i}: ")
    # Optionally convert input to int or float if desired
    list1.append(a)

result = list_to_arr(list1)
print(result)


Enter the number of elements:  10
Enter element 0:  1
Enter element 1:  2
Enter element 2:  3
Enter element 3:  4
Enter element 4:  5
Enter element 5:  6
Enter element 6:  7
Enter element 7:  8
Enter element 8:  9
Enter element 9:  10


['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


## 17. Create a NumPy array and demonstrate the use of numpy.view' to create a new array object with the same data.

In [12]:
import numpy as np

# Create a NumPy array
arr1 = np.array([1, 2, 3, 4])

# Demonstrate using view to create a new array object with the same data
arr2 = arr1.view()
print(arr2)


[1 2 3 4]


## 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [13]:
import numpy as np
arr1=np.array([[10,3],[3,7],[9,7]])
arr2=np.array([[11,30]])
axis=0
def concatenate_arr(arr1,arr2,axis=0):
    return np.concatenate((arr1,arr2),axis=axis)
concatenate_arr(arr1,arr2)

array([[10,  3],
       [ 3,  7],
       [ 9,  7],
       [11, 30]])

## 19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.

In [63]:
import numpy as np

print("Enter shape in this format (e1,e2,...2n)")

shape1=input("Enter the shape : ")
list1=shape1.split(",")
list1[0]=list1[0][1:]
list1[-1]=list1[-1][:-1]
shape1=tuple(map(int,list1))
arr1=np.array([])
num1=1
for i in shape1:
    num1*=i
for i in range(num1):
    a=int(input(f"Enter element {i+1} : "))
    arr1=np.append(arr1,a)
arr1=arr1.reshape(shape1)
print(f"arr1 : {arr1}")

shape2=input("Enter the shape : ")
list2=shape2.split(",")
list2[0]=list2[0][1:]
list2[-1]=list2[-1][:-1]
shape2=tuple(map(int,list2))
arr2=np.array([])
num2=1
for i in shape2:
    num2*=i
for i in range(num2):
    a=int(input(f"Enter element {i+1} : "))
    arr2=np.append(arr2,a)
arr2=arr2.reshape(shape2)
print(f"arr1 : {arr2}")
axis=0
print(f"Concatinated array : {np.concatenate((arr1,arr2),axis)}")

Enter shape in this format (e1,e2,...2n)


Enter the shape :  (2,3)
Enter element 1 :  10
Enter element 2 :  20
Enter element 3 :  30
Enter element 4 :  40
Enter element 5 :  50
Enter element 6 :  60


arr1 : [[10. 20. 30.]
 [40. 50. 60.]]


Enter the shape :  (1,3)
Enter element 1 :  1
Enter element 2 :  2
Enter element 3 :  3


arr1 : [[1. 2. 3.]]
Concatinated array : [[10. 20. 30.]
 [40. 50. 60.]
 [ 1.  2.  3.]]


## 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [1]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
def vertically_stacks(arr):
    return np.vstack(arr)
vertically_stacks([arr1,arr2,arr2])   

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [5, 6],
       [7, 8]])

## 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [2]:
import numpy as np
start=int(input("Enter the start : "))
stop=int(input("Enter the stop : "))
step=int(input("Enter the stept : "))

def array_create(start,stop,step):
    return np.arange(start,stop+1,step)
array_create(start,stop,step)

Enter the start :  1
Enter the stop :  10
Enter the stept :  2


array([1, 3, 5, 7, 9])

## 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [6]:
import numpy as np
start=0
stop=1
num=10

def array_create(start,stop,num):
    return np.linspace(start,stop,num)
array_create(start,stop,num)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1and 1000 (inclusive).

In [7]:
import numpy as np
start=1
stop=1000
num=5

def array_create(start,stop,num):
    return np.linspace(start,stop,num)
array_create(start,stop,num)

array([   1.  ,  250.75,  500.5 ,  750.25, 1000.  ])

## 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [9]:
import numpy as np
import pandas as pd
data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data)
print(df)

    0   1   2
0  20  83  60
1   2  19   3
2  59  20  35
3  20  79  83
4  53  94  42


## 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [55]:
import pandas as pd
import numpy as np
df=pd.DataFrame()
n=int(input("Enter the number of columns : "))
n1=int(input("Enter the number of elements in columns : "))
for i in range(n):
    key=input("Enter the column name : ")
    list1=[]
    for j in range(n1):
        a=int(input(f"Enter the value for element {j+1} : "))
        list1.append(a)
    df[key]=list1
    list1.clear()
print(df)
col=input("Enter the column name to convert -ve to zero : ")
def df_replace(df,col):
    df[col] = np.where(df[col] < 0, 0, df[col]) 
    return df
df_replace(df,col)

Enter the number of columns :  3
Enter the number of elements in columns :  3
Enter the column name :  a
Enter the value for element 1 :  -1
Enter the value for element 2 :  2
Enter the value for element 3 :  -3
Enter the column name :  b
Enter the value for element 1 :  -4
Enter the value for element 2 :  -5
Enter the value for element 3 :  6
Enter the column name :  c
Enter the value for element 1 :  7
Enter the value for element 2 :  -8
Enter the value for element 3 :  -9


   a  b  c
0 -1 -4  7
1  2 -5 -8
2 -3  6 -9


Enter the column name to convert -ve to zero :  a


a  b  c
0  0 -4  7
1  2 -5 -8
2  0  6 -9

## 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [30]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

##  27. Retrieve the element at index (1, 2) from the 2D NumPy array.
 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [37]:
import numpy as np 
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1, 2]

6

##  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 arr = np.array([3, 8, 2, 10, 5, 7])

In [38]:
import numpy as np
arr = np.array([3, 8, 2, 10, 5, 7])
arr>5

array([False,  True, False,  True, False,  True])

## 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

##  30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [47]:
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.array([arr_2d[0,1:3],arr_2d[1,1:3]])

array([[2, 3],
       [5, 6]])

## 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [75]:
import numpy as np
list1=[]
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)
row=int(input("Enter the number of row :"))
col=int(input("Enter the number of col :"))
arr1=arr1.reshape((row,col))
print(arr1)

n1=int(input("Enter the number of elements in index array : "))
index_lst=[]
for i in range(n1):
    row=int(input(f"row {i} :"))
    col=int(input(f"col {i} :"))
    index_lst.append((row,col))
index_arr=np.array(index_lst)
print(index_arr)

for i in index_arr:
    print("arr1[",i,"] =",arr1[i[0],i[1]])

Enter the number of elements in array :  10
Enter integer number :  1
Enter integer number :  2
Enter integer number :  3
Enter integer number :  4
Enter integer number :  5
Enter integer number :  6
Enter integer number :  7
Enter integer number :  8
Enter integer number :  9
Enter integer number :  10


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Enter the number of elements in index array :  4
row 0 : 0
col 0 : 1
row 1 : 1
col 1 : 3
row 2 : 0
col 2 : 4
row 3 : 1
col 3 : 0


[[0 1]
 [1 3]
 [0 4]
 [1 0]]
arr1[ [0 1] ] = 2
arr1[ [1 3] ] = 9
arr1[ [0 4] ] = 5
arr1[ [1 0] ] = 6


##  32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [78]:
import numpy as np
list1=[]
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)
print(arr1)
a=int(input("Enter the threshold :"))
def filter(arr1,a):
    return arr1[arr1>a]
filter(arr1,a)

Enter the number of elements in array :  10
Enter integer number :  -9
Enter integer number :  5
Enter integer number :  9
Enter integer number :  2
Enter integer number :  7
Enter integer number :  2
Enter integer number :  7
Enter integer number :  1
Enter integer number :  2
Enter integer number :  5


[-9  5  9  2  7  2  7  1  2  5]


Enter the threshold : 5


array([9, 7, 7])

##  33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [117]:
import numpy as np
list1=[]
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)

a=input("Enter the shape in the following format (e1,e2,e3) : ")
a=a.split(",")
a[0]=a[0][1:]
a[-1]=a[-1][:-1]
a=tuple(map(int,a))
print(a)

arr1=arr1.reshape(a[0],a[1],a[2])
print(arr1)

n1=int(input("Enter the number of elements : "))
print("Index arrays 1 ")
list1=[int(input(f"Enter the value for element {i+1} : ")) for i in range(n1)]
arr2=np.array(list1)
print(arr2)
print("Index arrays 2 ")
list2=[int(input(f"Enter the value for element {i+1} : ")) for i in range(n1)]
arr3=np.array(list2)
print(arr3)
print("Index arrays 3 ")
list3=[int(input(f"Enter the value for element {i+1} : ")) for i in range(n1)]
arr4=np.array(list3)
print(arr4)

list4=[arr1[arr2[i],arr3[i],arr4[i]] for i in range(n1)]
arr5=np.array(list4)
arr5

Enter the number of elements in array :  12
Enter integer number :  1
Enter integer number :  2
Enter integer number :  3
Enter integer number :  4
Enter integer number :  5
Enter integer number :  6
Enter integer number :  7
Enter integer number :  8
Enter integer number :  9
Enter integer number :  10
Enter integer number :  11
Enter integer number :  12
Enter the shape in the following format (e1,e2,e3) :  (2,3,2)


(2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Enter the number of elements :  3


Index arrays 1 


Enter the value for element 1 :  0
Enter the value for element 2 :  1
Enter the value for element 3 :  0


[0 1 0]
Index arrays 2 


Enter the value for element 1 :  0
Enter the value for element 2 :  1
Enter the value for element 3 :  2


[0 1 2]
Index arrays 3 


Enter the value for element 1 :  1
Enter the value for element 2 :  0
Enter the value for element 3 :  1


[1 0 1]


array([2, 9, 6])

##  34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [127]:
import numpy as np
list1=[]
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)
row=int(input("Enter the number of row :"))
col=int(input("Enter the number of col :"))
arr1=arr1.reshape((row,col))
def condition_arr(arr1):
    return arr1[(arr1>2) & (arr1%2==0)]
condition_arr(arr1)

Enter the number of elements in array :  6
Enter integer number :  1
Enter integer number :  6
Enter integer number :  7
Enter integer number :  3
Enter integer number :  8
Enter integer number :  12
Enter the number of row : 2
Enter the number of col : 3


array([ 6,  8, 12])

##  35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [129]:
import numpy as np
list1=[]
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)

a=input("Enter the shape in the following format (e1,e2) : ")#c
a=a.split(",")
a[0]=a[0][1:]
a[-1]=a[-1][:-1]
a=tuple(map(int,a))
print(a)

arr1=arr1.reshape(a[0],a[1])
print(arr1)

n1=int(input("Enter the number of elements : "))
print("Index arrays 1 ")
list1=[int(input(f"Enter the value for element {i+1} : ")) for i in range(n1)]
arr2=np.array(list1)
print(arr2)
print("Index arrays 2 ")
list2=[int(input(f"Enter the value for element {i+1} : ")) for i in range(n1)]
arr3=np.array(list2)
print(arr3)


list4=[arr1[arr2[i],arr3[i]] for i in range(n1)]
arr5=np.array(list4)
arr5

Enter the number of elements in array :  12
Enter integer number :  1
Enter integer number :  2
Enter integer number :  3
Enter integer number :  4
Enter integer number :  5
Enter integer number :  6
Enter integer number :  7
Enter integer number :  8
Enter integer number :  9
Enter integer number :  10
Enter integer number :  11
Enter integer number :  12
Enter the shape in the following format (e1,e2) :  (4,3)


(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Enter the number of elements :  3


Index arrays 1 


Enter the value for element 1 :  0
Enter the value for element 2 :  1
Enter the value for element 3 :  3


[0 1 3]
Index arrays 2 


Enter the value for element 1 :  2
Enter the value for element 2 :  1
Enter the value for element 3 :  0


[2 1 0]


array([ 3,  5, 10])

##  36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [131]:
import numpy as np
list1=[]
for i in range(9):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1)
arr1=arr1.reshape(3,3)
print(arr1)
arr1=arr1+5
print(arr1)

Enter integer number :  1
Enter integer number :  2
Enter integer number :  3
Enter integer number :  4
Enter integer number :  5
Enter integer number :  6
Enter integer number :  7
Enter integer number :  8
Enter integer number :  9


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


##  37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [14]:
import numpy as np

# Input for arr1 (1x3 array)
arr1 = np.array([1, 2, 3]).reshape(1, 3)
print("arr1:")
print(arr1)

# Input for arr2 (3x4 array)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
print("\narr2:")
print(arr2)

# Reshape arr1 to (3, 1) to match the broadcasting shape
arr1_reshaped = arr1.reshape(3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1_reshaped

print("\nResult of broadcasting multiplication:")
print(result)


arr1:
[[1 2 3]]

arr2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Result of broadcasting multiplication:
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


##  38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [16]:
import numpy as np

# Input for arr1 (1x4 array)
arr1 = np.array([1, 2, 3, 4]).reshape(1, 4)
print("arr1:")
print(arr1)

# Input for arr2 (4x3 array)
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
print("\narr2:")
print(arr2)

# Transpose arr1 to match the shape of arr2 for broadcasting
arr1_broadcasted = arr1.T  # Transpose to get a (4x1) array
print("\nBroadcasted arr1:")
print(arr1_broadcasted)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1_broadcasted

print("\nResult of broadcasting addition:")
print(result)


arr1:
[[1 2 3 4]]

arr2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Broadcasted arr1:
[[1]
 [2]
 [3]
 [4]]

Result of broadcasting addition:
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


##  39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [143]:
import numpy as np
list1=[]
for i in range(3):
    a=int(input("Enter integer number : "))
    list1.append(a)
arr1=np.array(list1).reshape(1,3)
print(arr1)  
list2=[]
for i in range(3):
    a=int(input("Enter integer number : "))
    list2.append(a)
arr2=np.array(list2).reshape(3,1)
print(arr2)  
arr1+arr2

Enter integer number :  1
Enter integer number :  2
Enter integer number :  3


[[1 2 3]]


Enter integer number :  4
Enter integer number :  5
Enter integer number :  6


[[4]
 [5]
 [6]]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

##  40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [17]:
import numpy as np

# Define arr1 and arr2
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # shape (2, 3)
arr2 = np.array([[1, 2],
                 [3, 4]])     # shape (2, 2)

# Check the shapes
print("arr1 shape:", arr1.shape)
print("arr2 shape:", arr2.shape)

# Reshape arr1 to (2, 3, 1) and arr2 to (2, 1, 2) for broadcasting
arr1_reshaped = arr1[:, :, np.newaxis]  # shape (2, 3, 1)
arr2_reshaped = arr2[:, np.newaxis, :]  # shape (2, 1, 2)

# Perform element-wise multiplication using broadcasting
result = arr1_reshaped * arr2_reshaped  # shape (2, 3, 2)

# Print the result
print("\nResult of broadcasting multiplication:")
print(result)


arr1 shape: (2, 3)
arr2 shape: (2, 2)

Result of broadcasting multiplication:
[[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[12 16]
  [15 20]
  [18 24]]]


##  41. Calculate column-wise mean for the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [155]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

##  42. Find maximum value in each row of the given array:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [157]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis=1)

array([3, 6])

## 43. For the given array, find indices of maximum value in each column.
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [39]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)

print(max_indices)

[1 1 1]


##  44. For the given array, apply custom function to calculate moving sum along rows.
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
import numpy as np
import pandas as pd

# Define the array arr
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Convert the NumPy array to a pandas DataFrame
df = pd.DataFrame(arr)

# Calculate the moving sum along rows with window size 2
moving_sum_df = df.rolling(window=2, axis=1).sum()

# Convert the pandas DataFrame back to a NumPy array
result = moving_sum_df.to_numpy()

print("Original array:")
print(arr)
print("\nMoving sum along rows with window size 2:")
print(result)


Original array:
[[1 2 3]
 [4 5 6]]

Moving sum along rows with window size 2:
[[nan  3.  5.]
 [nan  9. 11.]]


C:\Users\bluea\AppData\Local\Temp\ipykernel_20548\2255810926.py:12: FutureWarning: Support for axis=1 in DataFrame.rolling is deprecated and will be removed in a future version. Use obj.T.rolling(...) instead
  moving_sum_df = df.rolling(window=2, axis=1).sum()


##  45. In the given array, check if all elements in each column are even.
 arr = np.array([[2, 4, 6], [3, 5, 7]])

In [23]:
import numpy as np

arr = np.array([[2, 4, 6], 
                [3, 5, 7]])

# Get the dimensions of the array
rows, cols = arr.shape

# Initialize a flag to check if all elements in each column are even
all_even = True

# Iterate over each column
for col in range(cols):
    # Initialize a flag for the current column
    column_even = True
    # Iterate over each element in the current column
    for row in range(rows):
        # Check if the element is even
        if arr[row, col] % 2 != 0:
            column_even = False
            break
    # If any element in the column is not even, set the flag to False
    if not column_even:
        all_even = False
        break

# Output the result
if all_even:
    print("All elements in each column are even.")
else:
    print("Not all elements in each column are even.")


Not all elements in each column are even.


## 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
 original_array = np.array([1, 2, 3, 4, 5, 6])

In [173]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
row=int(input("row = :"))
col=int(input("col = :"))
np.matrix(original_array).reshape(row,col)

row = : 3
col = : 2


matrix([[1, 2],
        [3, 4],
        [5, 6]])

##  47. Create a function that takes a matrix as input and returns the flattened array.
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [174]:
import numpy as np
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flattene_arr(arr):
    return arr.flatten()
flattene_arr(input_matrix)

array([1, 2, 3, 4, 5, 6])

## 48. Write a function that concatenates two given arrays along a specified axis.
 array1 = np.array([[1, 2], [3, 4]])

 array2 = np.array([[5, 6], [7, 8]])

In [177]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
axis=int(input("axis : "))
def concatenate_arr(array1,array2,axis):
    return np.concatenate((array1,array2),axis=axis)
concatenate_arr(array1,array2,axis)

axis :  1


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##  49. Create a function that splits an array into multiple sub-arrays along a specified axis.
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [43]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.split(original_array,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

##  50. Write a function that inserts and then deletes elements from a given array at specified indices.
 original_array = np.array([1, 2, 3, 4, 5])

 
 indices_to_insert = [2, 4]

 
 values_to_insert = [10, 11]

 
 indices_to_delete = [1, 3] 

In [29]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

original_array = np.insert(original_array,indices_to_insert[0],values_to_insert[0])
original_array = np.insert(original_array,indices_to_insert[1],values_to_insert[1])

original_array = np.delete(original_array,indices_to_delete[0])
original_array = np.delete(original_array,indices_to_delete[1])

original_array

array([ 1, 10,  3,  4,  5])

## 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [167]:
import numpy as np
arr1=np.array([np.random.randint(1,11) for i in range(10)])
print(arr1)
arr2=np.array([np.random.randint(1,11) for i in range(10)])
print(arr2)
print(arr1+arr2)

[7 6 1 7 1 9 8 1 7 9]
[4 9 3 5 3 1 3 3 8 5]
[11 15  4 12  4 10 11  4 15 14]


##  52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [170]:
import numpy as np
arr1=np.arange(10,0,-1)
print(arr1)
arr2=np.arange(1,11)
print(arr2)
print(arr1-arr2)

[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


##  53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [171]:
import numpy as np
arr1=np.array([np.random.randint(1,6) for i in range(10)])
print(arr1)
arr2=np.array([np.random.randint(1,6) for i in range(10)])
print(arr2)
print(arr1*arr2)

[4 5 1 1 4 4 3 2 4 3]
[5 5 4 2 5 3 3 1 5 2]
[20 25  4  2 20 12  9  2 20  6]


##  54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [173]:
import numpy as np
arr1=np.arange(2,11)
arr1=arr1[arr1%2==0]
print(arr1)
arr2=np.arange(1,6)
print(arr2)
print(arr1/arr2)

[ 2  4  6  8 10]
[1 2 3 4 5]
[2. 2. 2. 2. 2.]


##  55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [174]:
import numpy as np
arr1=np.arange(1,6)
print(arr1)
arr2=np.arange(5,0,-1)
print(arr2)
print(arr1**arr2)

[1 2 3 4 5]
[5 4 3 2 1]
[ 1 16 27 16  5]


##  56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [183]:
import numpy as np
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
sub_str=input("Enter the sub string : ")
def count_sub_str(arr,sub_str):
    count=0
    for i in arr:
        if(i.count(sub_str) >0):
            count+=i.count(sub_str)
    return count
count_sub_str(arr,sub_str)

Enter the sub string :  lo


3

## 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])


In [184]:
import numpy as np
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extracts_upper(arr):
    for i in arr:
        for j in range(len(i)):
            if(i[j].isupper()):
                print(i[j])
extracts_upper(arr)

H
W
O
A
I
G
P
T


## 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [2]:
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
sub_str=input("Enter the sub string : ")
new_str=input("Enter the new string : ")
def count_sub_str(arr,sub_str,new_str):
    for i in range(len(arr)):
        if(arr[i].count(sub_str) >0):
            for j in range(arr[i].count(sub_str)):
                arr[i]=arr[i].replace(sub_str,new_str)
            
    return arr
count_sub_str(arr,sub_str,new_str)

Enter the sub string :  p
Enter the new string :  OO


array(['aOOOOle', 'banana', 'graOOe', 'OOineaOOO'], dtype='<U9')

##  59. Write a function that concatenates strings in a NumPy array element-wise.
 arr1 = np.array(['Hello', 'World'])

 
 arr2 = np.array(['Open', 'AI'])

In [4]:
import numpy as np
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_str(arr):
    temp=""
    for i in arr:
        temp+=i
    return temp
print(concatenate_str(arr1))
print(concatenate_str(arr2))

HelloWorld
OpenAI


## 60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [5]:
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def len_long_str(arr):
    max=arr[0]
    for i in arr:
        if(len(i)>len(max)):
            max=i
    return max
len_long_str(arr)

'pineapple'

##  61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [9]:
import numpy as np
dataset=np.array([np.random.randint(1,1001) for i in range(100)])
print(dataset)
print(f"mean = {np.mean(dataset)}\nmedian= {np.median(dataset)}\nvariance= {np.var(dataset)}\nstandard deviation= {np.std(dataset)}")

[292 233 740 335 700 585 983 886  99 802 370 566 449 127 920 654 792 328
 911 142 553 726 490 581 346  14 804 282 693 807 581 126 447 748 966 840
 992 989 628  18 768 875 758 207 790 565 816 755 115 137  75  77 488 213
 806 574 258 198 446 756 437 976 579 404 755 309 930 602 699 414 865 665
 383  44 409 392 427 823 980 859 785 423  75 482 227 470 556 434 483 411
 592 810 874 345 238 509 307 733 545 904]
mean = 543.77
median= 560.5
variance= 74010.73710000001
standard deviation= 272.0491446411843


##  62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [38]:
import numpy as np

df=np.array([np.random.randint(1,101) for i in range(50)])
percentiles = np.percentile(random_integers, [25, 75])
print(percentiles[0])
print(percentiles[1])

311.0
841.0


##  63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [15]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,120,30,40,50])
np.corrcoef(arr1,arr2)

array([[1., 0.],
       [0., 1.]])

## 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [20]:
import numpy as np
arr1=np.matrix([[1,2,3],
                [4,5,6]])
arr2=np.matrix([[10,120,30],
                [12,40,50],
               [12,40,50]])
np.dot(arr1,arr2)

matrix([[ 70, 320, 280],
        [172, 920, 670]])

##  65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [39]:
import numpy as np

random_integers = np.random.randint(10, 1001, 50)


percentiles = np.percentile(random_integers, [10, 25, 50, 75, 90])


tenth_percentile = percentiles[0]
first_quartile = percentiles[1]
median = percentiles[2]
third_quartile = percentiles[3]
ninetieth_percentile = percentiles[4]

random_integers, tenth_percentile, first_quartile, median, third_quartile, ninetieth_percentile


(array([271, 225, 156, 345, 177, 101, 362, 580, 580, 825, 690, 790, 372,
        566, 354, 702, 179, 365, 200, 676, 431, 709,  16, 142, 756, 566,
        835, 770,  40, 544, 435, 403, 681, 372, 446, 679, 560, 936,  91,
        365, 267, 727, 598, 998, 533, 304, 971, 233, 534,  55]),
 137.9,
 268.0,
 440.5,
 680.5,
 793.5)

## 66. Create a NumPy array of integers and find the index of a specific element.

In [8]:
import numpy as np
arr=np.array([])
n=int(input("Enter the number of elements in array : "))
for i in range(n):
    a=int(input("Enter integer number : "))
    arr=np.append(arr,a)
element=int(input("Enter the element to find index : "))
index=np.where(arr == element)
index

Enter the number of elements in array :  4
Enter integer number :  1
Enter integer number :  9
Enter integer number :  4
Enter integer number :  0
Enter the element to find index :  4


(array([2], dtype=int64),)

## 67. Generate a random NumPy array and sort it in ascending order.

In [26]:
import numpy as np

arr = np.random.randint(10, 1001, 50) 
arr_sorted = np.sort(arr) 

arr_sorted


array([ 36,  81, 104, 145, 187, 197, 201, 213, 217, 239, 239, 246, 327,
       351, 378, 386, 434, 466, 477, 493, 500, 517, 560, 563, 596, 616,
       623, 645, 648, 648, 653, 656, 656, 664, 695, 712, 723, 727, 761,
       762, 800, 848, 858, 880, 893, 893, 911, 947, 967, 984])

## 68. Filter elements >20  in the given NumPy array.
 arr = np.array([12, 25, 6, 42, 8, 30])

In [15]:
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

##  69. Filter elements which are divisible by 3 from a given NumPy array.
 arr = np.array([1, 5, 8, 12, 15])

In [16]:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

##  70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
 arr = np.array([10, 20, 30, 40, 50])

In [17]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

##  71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])

In [27]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int64)
arr.dtype

dtype('int64')

## 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [1]:
import numpy as np

original_array = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:")
print(original_array)

original_array.byteswap(inplace=True)
print("\nArray after byte swapping in place:")
print(original_array)


Original array:
[    1   256 65536]

Array after byte swapping in place:
[16777216    65536      256]


##  73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [2]:
import numpy as np


original_array = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:")
print(original_array)
print("Original array byte order:", original_array.dtype.byteorder)

new_byte_order_array = original_array.newbyteorder()
print("\nNew byte order array:")
print(new_byte_order_array)
print("New byte order array byte order:", new_byte_order_array.dtype.byteorder)


Original array:
[    1   256 65536]
Original array byte order: =

New byte order array:
[16777216    65536      256]
New byte order array byte order: >


## 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [35]:
import numpy as np

# Create a NumPy array with a specific data type
original_array = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(original_array)

# Check the system's endianness
system_endianness = np.dtype('<i').byteorder

if system_endianness == '=':
    print("\nSystem endianness is native (=", "little-endian" if np.little_endian else "big-endian", ")")
else:
    print("\nSystem endianness is non-native (", "little-endian" if system_endianness == '<' else "big-endian", ")")

# Conditionally swap the byte order based on system endianness
if system_endianness == '<':
    # System is little-endian, swap to big-endian
    swapped_array = original_array.newbyteorder('>')
elif system_endianness == '>':
    # System is big-endian, swap to little-endian
    swapped_array = original_array.newbyteorder('<')
else:
    # System endianness is native ('='), so determine based on np.little_endian
    if np.little_endian:
        # Swap to big-endian
        swapped_array = original_array.newbyteorder('>')
    else:
        # Swap to little-endian
        swapped_array = original_array.newbyteorder('<')

print("\nSwapped byte order array:")
print(swapped_array)


Original array:
[1 2 3]

System endianness is native (= little-endian )

Swapped byte order array:
[16777216 33554432 50331648]


##  75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [36]:
import numpy as np

# Create a NumPy array with a specific data type (here int32)
original_array = arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:")
print(original_array)

# Check the byte order attribute of the dtype
array_byte_order = original_array.dtype.byteorder
print("\nByte order attribute of dtype:", array_byte_order)

# Determine if byte swapping is necessary
if array_byte_order == '=':
    print("System byte order matches array's byte order (no byte swapping needed).")
else:
    print("Byte swapping is necessary for the current system.")


Original array:
[1 2 3]

Byte order attribute of dtype: =
System byte order matches array's byte order (no byte swapping needed).


## 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [37]:
import numpy as np

# Create arr1 with values from 1 to 10
arr1 = np.arange(1, 11)
print("Original array arr1:")
print(arr1)

# Create a deep copy using copy() method
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Check if modifying copy_arr affects arr1
print("\nAfter modifying copy_arr:")
print("arr1:", arr1)
print("copy_arr:", copy_arr)


Original array arr1:
[ 1  2  3  4  5  6  7  8  9 10]

After modifying copy_arr:
arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


##  77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [48]:
import numpy as np
matrix=np.matrix([np.random.randint(1,20,9)]).reshape(3,3)
print(matrix)
view_slice=matrix[1:3,0:2]
print(view_slice)
view_slice[0,0]=100
print("After changing ")
print(view_slice)
print(matrix)

[[10 12 15]
 [ 6 14 11]
 [10  1  9]]
[[ 6 14]
 [10  1]]
After changing 
[[100  14]
 [ 10   1]]
[[ 10  12  15]
 [100  14  11]
 [ 10   1   9]]


## 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`

In [53]:
import numpy as np
array_a=np.arange(1,13).reshape(4,3)
print(array_a)
view=array_a[1:3,1:3]
print(view)
view+=5
print(view)
print(array_a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[5 6]
 [8 9]]
[[10 11]
 [13 14]]
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


##  79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`

In [56]:
import numpy as np
orig_array=np.array([np.random.randint(1,9,8)]).reshape(2,4)
print(orig_array)
reshaped_view=orig_array.reshape(4,2)
print(reshaped_view)
print(orig_array)

[[1 8 4 4]
 [6 7 2 3]]
[[1 8]
 [4 4]
 [6 7]
 [2 3]]
[[1 8 4 4]
 [6 7 2 3]]


##  80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [59]:
import numpy as np
data=np.array([np.random.randint(1,20,12)]).reshape(3,4)
print(data)
data_copy=data[data>5]
print(data_copy)
data_copy+=10
print(data_copy)
print(data)

[[ 9 14  3  3]
 [13 19  7  7]
 [ 1 14  6 17]]
[ 9 14 13 19  7  7 14  6 17]
[19 24 23 29 17 17 24 16 27]
[[ 9 14  3  3]
 [13 19  7  7]
 [ 1 14  6 17]]


##  81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [64]:
import numpy as np
matrix1=np.matrix([np.random.randint(1,20,12)]).reshape(3,4)
matrix2=np.matrix([np.random.randint(1,20,12)]).reshape(3,4)
print(matrix1)
print(matrix2)
print(matrix1+matrix2)
print(matrix1-matrix2)

[[14  3  7  2]
 [14  9  4 10]
 [19 15 11  1]]
[[ 6 19 11 15]
 [15 18 16 12]
 [10  2 18 15]]
[[20 22 18 17]
 [29 27 20 22]
 [29 17 29 16]]
[[  8 -16  -4 -13]
 [ -1  -9 -12  -2]
 [  9  13  -7 -14]]


##  82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [5]:
import numpy as np
C=np.matrix([int(input("Matrix 1 Enter element value : ")) for i in range(6)]).reshape(3,2)
print(C)
D=np.matrix([int(input("Matrix 2 Enter element value : ")) for i in range(8)]).reshape(2,4)
print(D)
C@D

Matrix 1 Enter element value :  1
Matrix 1 Enter element value :  8
Matrix 1 Enter element value :  4
Matrix 1 Enter element value :  7
Matrix 1 Enter element value :  4
Matrix 1 Enter element value :  2


[[1 8]
 [4 7]
 [4 2]]


Matrix 2 Enter element value :  7
Matrix 2 Enter element value :  3
Matrix 2 Enter element value :  7
Matrix 2 Enter element value :  2
Matrix 2 Enter element value :  7
Matrix 2 Enter element value :  4
Matrix 2 Enter element value :  8
Matrix 2 Enter element value :  2


[[7 3 7 2]
 [7 4 8 2]]


matrix([[63, 35, 71, 18],
        [77, 40, 84, 22],
        [42, 20, 44, 12]])

##  83. Create a matrix `E` and find its transpose.

In [66]:
import numpy as np
E=np.matrix([np.random.randint(1,20,12)]).reshape(3,4)
print(E)
print(E.T)

[[ 4 12  4 10]
 [ 1 19 14  1]
 [ 8 18  9  8]]
[[ 4  1  8]
 [12 19 18]
 [ 4 14  9]
 [10  1  8]]


##  84. Generate a square matrix `F` and compute its determinant.

In [69]:
import numpy as np
F=np.matrix([np.random.randint(1,20,16)]).reshape(4,4)
print(F)
print( np.linalg.det(F))

[[15  5 16 16]
 [ 3  2  5  5]
 [ 7  8 17  4]
 [ 4  1  8 14]]
784.9999999999998


##  85. Create a square matrix `G` and find its inverse.

In [28]:
import numpy as np

# Define matrix G
G = np.matrix([
    [ 2, 12, 14, 17],
    [ 3, 16,  4,  9],
    [ 3,  5, 17, 19],
    [ 5,  4, 12, 10]
])

# Calculate the inverse of G
G_inv = np.linalg.inv(G)

print("Matrix G:")
print(G)
print("\nInverse of G:")
print(G_inv)


Matrix G:
[[ 2 12 14 17]
 [ 3 16  4  9]
 [ 3  5 17 19]
 [ 5  4 12 10]]

Inverse of G:
[[-0.39610964  0.20689655  0.19451813  0.11759505]
 [ 0.15694076 -0.01724138 -0.15296198  0.03934571]
 [ 0.37356322 -0.22413793 -0.32183908  0.17816092]
 [-0.31299735  0.17241379  0.35013263 -0.18832891]]
